from __future__ import annotations

import json
import re
import shlex
import shutil
import time
import zipfile
from pathlib import Path

from .config import OrbitConfig
from .training_config import TrainingConfig


def create_job_bundle(
    root: Path, preset: str, steps: int, batch_size: int, seq_len: int,
    learning_rate: float, text: str, name: str = "orbit-training",
    training_config: TrainingConfig | None = None, model_name: str = "orbit",
    data_language: str = "bilingual",
) -> Path:
    """Create a portable remote-GPU training job without running it locally."""
    if preset not in {"local", "300m", "1b", "3b", "7b", "14b", "38b"}:
        raise ValueError("unsupported model preset")
    if steps < 1 or batch_size < 1 or seq_len < 2:
        raise ValueError("steps, batch size and sequence length must be positive")
    cfg = OrbitConfig.for_preset(preset)
    train_cfg = training_config or TrainingConfig.for_model(preset).with_overrides(
        steps=steps, batch_size=batch_size, seq_len=seq_len, learning_rate=learning_rate,
    )
    train_cfg.validate()
    model_name = "-".join(model_name.strip().split()) or "orbit"
    if not re.fullmatch(r"[\w.-]{1,80}", model_name, flags=re.UNICODE):
        raise ValueError("invalid model name")
    job_id = f"{int(time.time())}-{preset}"
    job_dir = root / f"{name}-{job_id}"
    job_dir.mkdir(parents=True, exist_ok=False)
    config = {
        "job_id": job_id,
        "preset": preset,
        "model_parameters": cfg.estimate_parameters(),
        "model_name": model_name,
        "identity": "Orbit",
        "data_language": data_language,
        "training": train_cfg.__dict__,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    }
    (job_dir / "job.json").write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")
    (job_dir / "dataset.txt").write_text(text, encoding="utf-8")
    project_dir = job_dir / "orbit_project"
    project_dir.mkdir()
    project_root = Path(__file__).resolve().parents[1]
    shutil.copy2(project_root / "pyproject.toml", project_dir / "pyproject.toml")
    shutil.copytree(project_root / "orbit", project_dir / "orbit")
    command = (
        "python3 -m orbit.train"
        f" --preset {shlex.quote(preset)}"
        f" --data dataset.txt --steps {train_cfg.steps} --batch-size {train_cfg.batch_size}"
        f" --seq-len {train_cfg.seq_len} --grad-accum {train_cfg.grad_accum}"
        f" --lr {train_cfg.learning_rate} --warmup-steps {train_cfg.warmup_steps}"
        f" --weight-decay {train_cfg.weight_decay} --grad-clip {train_cfg.grad_clip}"
        f" --precision {train_cfg.precision} --scheduler {train_cfg.scheduler}"
        f" --checkpoint-every {train_cfg.checkpoint_every} --seed {train_cfg.seed} --device cuda"
        f" --model-name {shlex.quote(model_name)} --checkpoint {shlex.quote('../' + model_name + '.pt')}"
    )
    (job_dir / "run.sh").write_text(
        "#!/bin/sh\nset -eu\ncd orbit_project\npython3 -m pip install -e .\n" + command.replace("dataset.txt", "../dataset.txt") + "\n",
        encoding="utf-8",
    )
    (job_dir / "REMOTE_TRAINING.md").write_text(
        "# Orbit remote training job\n\n"
        "This bundle is generated by the Orbit graphical trainer. It is not executed on the control computer.\n\n"
        "1. Copy this directory into a machine with a supported CUDA GPU.\n"
        "2. Run `sh run.sh`; the bundle contains the required Orbit source.\n"
        f"3. Keep `{model_name}.pt` and training logs as the output artifacts.\n"
        "\n"
        f"Estimated architecture size: {cfg.estimate_parameters()/1e9:.3f}B parameters.\n",
        encoding="utf-8",
    )
    zip_path = job_dir.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for file in job_dir.rglob("*"):
            if file.is_file():
                archive.write(file, arcname=f"{job_dir.name}/{file.relative_to(job_dir)}")
    return zip_path
