PAGE = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>Orbit</title>
  <style>
    :root{font:16px/1.5 -apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",sans-serif;color:#182033;background:#eef3fa;--ink:#182033;--muted:#68748a;--line:rgba(45,61,88,.12);--glass:rgba(255,255,255,.68);--solid:#fff;--blue:#1769ff;--blue2:#6b5cff;--green:#16a36a;--red:#d84a54}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 0%,#dce9ff 0,transparent 34%),radial-gradient(circle at 94% 12%,#e6ddff 0,transparent 32%),#eef3fa;color:var(--ink)}
    button,input,select,textarea{font:inherit}button{touch-action:manipulation}.shell{max-width:1180px;margin:auto;padding:24px}.topbar{position:sticky;top:18px;z-index:20;display:flex;align-items:center;justify-content:space-between;padding:11px 13px 11px 20px;border:1px solid rgba(255,255,255,.8);border-radius:22px;background:rgba(255,255,255,.64);backdrop-filter:blur(28px) saturate(180%);box-shadow:0 16px 44px rgba(41,62,101,.12)}
    .brand{display:flex;align-items:center;gap:10px;font-weight:780;letter-spacing:-.02em}.mark{width:30px;height:30px;display:block;border-radius:7px;filter:drop-shadow(0 3px 4px rgba(0,0,0,.12))}.nav{display:flex;gap:4px;padding:3px;background:rgba(95,112,143,.10);border-radius:14px}.nav button{border:0;background:transparent;color:var(--muted);padding:8px 14px;border-radius:11px;font-weight:650;cursor:pointer}.nav button.active{background:var(--solid);color:var(--ink);box-shadow:0 3px 12px rgba(31,45,75,.10)}
    .hero{padding:64px 8px 34px}.eyebrow{color:var(--blue);font-size:.82rem;font-weight:760;letter-spacing:.08em;text-transform:uppercase}.hero h1{font-size:clamp(2.6rem,7vw,5.4rem);line-height:.96;letter-spacing:-.06em;margin:8px 0 18px;max-width:780px}.hero p{font-size:1.08rem;color:var(--muted);max-width:650px;margin:0}.local-pill{display:inline-flex;align-items:center;gap:8px;margin-top:22px;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,.62);border:1px solid rgba(255,255,255,.84);color:var(--muted);font-size:.88rem}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(22,163,106,.12)}
    .page{display:none;animation:materialize .28s cubic-bezier(.2,.8,.2,1)}.page.active{display:block}@keyframes materialize{from{opacity:0;transform:scale(.985);filter:blur(5px)}to{opacity:1;transform:none;filter:none}}
    .grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.card{background:var(--glass);backdrop-filter:blur(24px) saturate(160%);border:1px solid rgba(255,255,255,.82);border-radius:26px;padding:24px;box-shadow:0 18px 54px rgba(36,54,88,.10)}.card h2{font-size:1.25rem;letter-spacing:-.025em;margin:0 0 5px}.muted{color:var(--muted)}.small{font-size:.86rem}.stack{display:grid;gap:14px}.field{display:grid;gap:6px}.field label{font-size:.86rem;font-weight:700;color:#39445a}input,select,textarea{width:100%;border:1px solid var(--line);background:rgba(255,255,255,.78);color:var(--ink);border-radius:13px;padding:11px 12px;outline:none;transition:border-color .15s,box-shadow .15s}input:focus,select:focus,textarea:focus{border-color:rgba(23,105,255,.55);box-shadow:0 0 0 4px rgba(23,105,255,.10)}textarea{resize:vertical;min-height:160px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:16px}.button{border:0;border-radius:13px;padding:11px 16px;font-weight:730;cursor:pointer;background:#e8edf7;color:var(--ink);transition:transform .1s,filter .15s}.button.primary{color:#fff;background:linear-gradient(135deg,var(--blue),var(--blue2));box-shadow:0 9px 24px rgba(38,89,223,.25)}.button.danger{color:var(--red);background:rgba(216,74,84,.10)}.button:active{transform:scale(.97)}.button:disabled{opacity:.45;cursor:not-allowed}.status{padding:14px;border-radius:16px;background:rgba(241,245,252,.76);border:1px solid var(--line)}.status-line{display:flex;justify-content:space-between;gap:12px}.progress{height:8px;background:rgba(84,101,132,.12);border-radius:999px;overflow:hidden;margin-top:11px}.progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--blue),var(--blue2));border-radius:inherit;transition:width .25s ease}.model-list{display:grid;gap:9px}.model{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.55)}.model b{display:block}.badge{font-size:.75rem;font-weight:720;border-radius:999px;padding:4px 8px;background:rgba(23,105,255,.10);color:var(--blue)}
    .chat{height:510px;display:flex;flex-direction:column}.messages{flex:1;overflow:auto;padding:4px 2px 14px;display:flex;flex-direction:column;gap:10px}.bubble{max-width:82%;padding:11px 14px;border-radius:17px;white-space:pre-wrap;overflow-wrap:anywhere}.bubble.user{align-self:flex-end;background:linear-gradient(135deg,var(--blue),var(--blue2));color:#fff;border-bottom-right-radius:5px}.bubble.assistant{align-self:flex-start;background:rgba(255,255,255,.82);border:1px solid var(--line);border-bottom-left-radius:5px}.composer{display:flex;gap:9px}.composer input{flex:1}.empty{text-align:center;color:var(--muted);padding:70px 20px}.code{position:relative;background:#111827;color:#e6edf8;border-radius:16px;padding:17px;overflow:auto;font:13px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap}.copy{position:absolute;right:8px;top:8px;border:0;border-radius:9px;padding:6px 9px;background:#293448;color:#fff;cursor:pointer}.api-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px 0;border-bottom:1px solid var(--line)}.api-row:last-child{border:0}.api-value{font:13px ui-monospace,SFMono-Regular,Menlo,monospace;overflow-wrap:anywhere}.toast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,20px);opacity:0;background:#151d2c;color:white;padding:10px 15px;border-radius:12px;pointer-events:none;transition:.2s;z-index:40}.toast.show{opacity:1;transform:translate(-50%,0)}details{margin-top:14px}summary{cursor:pointer;color:var(--muted);font-weight:650;padding:5px 0}.footer{text-align:center;color:var(--muted);font-size:.82rem;padding:32px 0 12px}
    @media(max-width:800px){.shell{padding:12px}.topbar{top:8px;padding-left:14px}.nav button{padding:8px 10px}.grid{grid-template-columns:1fr}.hero{padding:42px 5px 26px}.card{padding:18px;border-radius:22px}.form-grid{grid-template-columns:1fr}.chat{height:62vh}.brand span:last-child{display:none}}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.page{animation:opacity .15s}.button,.progress span{transition:none}}
    @media(prefers-reduced-transparency:reduce){.topbar,.card{background:#fff;backdrop-filter:none}}
    @media(prefers-contrast:more){.topbar,.card,input,select,textarea{background:#fff;border-color:#4d596d}}
    @media(prefers-color-scheme:dark){:root{--ink:#f4f7fc;--muted:#aab5c8;--line:rgba(222,232,249,.14);--glass:rgba(20,27,40,.72);--solid:#242d3e}body{background:radial-gradient(circle at 15% 0%,#19315b 0,transparent 33%),radial-gradient(circle at 90% 10%,#342453 0,transparent 30%),#0d121c}.topbar{background:rgba(18,25,38,.7);border-color:rgba(255,255,255,.12)}input,select,textarea,.bubble.assistant,.model{background:rgba(33,43,61,.82)}.status{background:rgba(27,36,52,.76)}.field label{color:#cbd4e3}}
  </style>
</head>
<body><div class="shell">
  <header class="topbar"><div class="brand"><img class="mark" src="/static/orbit-logo.png" alt=""><span>Orbit</span></div><nav class="nav"><button data-page="chat" class="active">对话</button><button data-page="train">训练</button><button data-page="api">API</button></nav></header>
  <section class="hero"><div class="eyebrow">Local AI Studio</div><h1>在你的电脑上，训练你的模型。</h1><p>数据、checkpoint、对话和 API 都留在本机。训练完成后，Orbit 可以直接接入这台电脑里的智能体。</p><div class="local-pill"><span class="dot"></span>本地服务 · <span id="serverAddress">127.0.0.1:8765</span></div></section>

  <main id="chat" class="page active"><div class="grid">
    <section class="card chat"><div class="status-line"><div><h2>本地对话</h2><div class="muted small">消息只发送给当前加载的本地模型</div></div><span class="badge" id="chatModelBadge">未加载</span></div><div class="messages" id="messages"><div class="empty">训练或加载一个模型后，就可以在这里对话。</div></div><div class="composer"><input id="prompt" placeholder="给 Orbit 发送消息…" autocomplete="off"><button class="button primary" id="sendButton">发送</button></div></section>
    <aside class="card"><h2>本地模型</h2><p class="muted small">选择一个 checkpoint。模型只从本机目录读取。</p><div id="models" class="model-list"></div><div class="actions"><button class="button" id="refreshModels">刷新模型</button><button class="button" data-go="train">开始训练</button></div></aside>
  </div></main>

  <main id="train" class="page"><div class="grid">
    <section class="card"><h2>创建训练</h2><p class="muted small">本机训练会先检查内存；超出本机能力的档位可导出到 CUDA GPU 服务器。</p><div class="form-grid">
      <div class="field"><label for="preset">模型规模</label><select id="preset"><option value="300m">Orbit 300M</option><option value="1b">Orbit 1B</option><option value="3b">Orbit 3B</option><option value="7b">Orbit 7B</option><option value="14b">Orbit 14B</option><option value="38b">Orbit 38B</option></select></div>
      <div class="field"><label for="steps">训练步数</label><input id="steps" type="number" value="100" min="1"></div>
      <div class="field"><label for="batch">批大小</label><input id="batch" type="number" value="1" min="1"></div>
      <div class="field"><label for="seq">序列长度</label><input id="seq" type="number" value="256" min="2"></div>
      <div class="field"><label for="device">设备</label><select id="device"><option value="auto">自动选择</option><option value="mps">Apple GPU (MPS)</option><option value="cuda">NVIDIA GPU (CUDA)</option><option value="cpu">CPU</option></select></div>
      <div class="field"><label for="lr">学习率</label><input id="lr" type="number" value="0.0003" step="0.00001"></div>
    </div><div class="field" style="margin-top:14px"><label for="corpus">用户自己的训练文本</label><textarea id="corpus" placeholder="在这里粘贴文本。内容不会上传。"></textarea></div>
    <details><summary>高级训练参数</summary><div class="form-grid">
      <div class="field"><label for="accum">梯度累积</label><input id="accum" type="number" value="1" min="1"></div><div class="field"><label for="warmup">Warmup</label><input id="warmup" type="number" value="10" min="0"></div><div class="field"><label for="decay">权重衰减</label><input id="decay" type="number" value="0.1" step="0.01"></div><div class="field"><label for="clip">梯度裁剪</label><input id="clip" type="number" value="1" step="0.1"></div><div class="field"><label for="precision">精度</label><select id="precision"><option>auto</option><option>fp16</option><option>bf16</option><option>fp32</option></select></div><div class="field"><label for="save">保存间隔</label><input id="save" type="number" value="100" min="0"></div>
    </div></details><div class="actions"><button class="button primary" id="startTraining">在本机开始训练</button><button class="button" id="createRemote">生成远程 GPU 任务包</button></div></section>
    <aside class="stack"><section class="card"><h2>设备评估</h2><div id="estimate" class="status">正在检查本机资源…</div></section><section class="card"><h2>训练进度</h2><div id="trainingStatus" class="status"><div class="status-line"><b>待机</b><span>0 / 0</span></div><div class="progress"><span></span></div><div class="muted small" style="margin-top:9px">尚未开始训练</div></div><div class="actions"><button class="button danger" id="stopTraining">停止并保存</button></div></section><section class="card"><h2>远程任务</h2><div id="jobs" class="muted small">暂无任务</div></section></aside>
  </div></main>

  <main id="api" class="page"><div class="grid">
    <section class="card"><h2>本机 OpenAI 兼容 API</h2><p class="muted">训练完成后，电脑里的智能体可以按 OpenAI 接口调用 Orbit，不需要把模型或对话发到互联网。</p><div class="api-row"><span>Base URL</span><span class="api-value" id="baseUrl">http://127.0.0.1:8765/v1</span></div><div class="api-row"><span>API Key</span><span class="api-value">orbit-local（本机接口不校验）</span></div><div class="api-row"><span>当前模型</span><span class="api-value" id="apiModel">尚未加载</span></div><h3>智能体配置</h3><div class="code" id="agentCode"><button class="copy">复制</button>{
  "provider": "openai-compatible",
  "base_url": "http://127.0.0.1:8765/v1",
  "api_key": "orbit-local",
  "model": "你的本地模型名称"
}</div><h3>Python</h3><div class="code"><button class="copy">复制</button>from openai import OpenAI

client = OpenAI(
    base_url="http://127.0.0.1:8765/v1",
    api_key="orbit-local",
)
reply = client.chat.completions.create(
    model="你的本地模型名称",
    messages=[{"role": "user", "content": "你好"}],
)
print(reply.choices[0].message.content)</div></section>
    <aside class="stack"><section class="card"><h2>接口</h2><div class="api-row"><span>模型列表</span><span class="api-value">GET /v1/models</span></div><div class="api-row"><span>聊天补全</span><span class="api-value">POST /v1/chat/completions</span></div></section><section class="card"><h2>隐私边界</h2><p class="muted small">服务默认只监听 127.0.0.1，同一局域网和互联网无法直接访问。安装依赖可能需要联网；完成安装后，本地训练、推理和 API 不依赖网络。</p></section></aside>
  </div></main>
  <footer class="footer">Orbit · Local by default</footer>
</div><div id="toast" class="toast"></div>
<script>
const $=id=>document.getElementById(id);let system=null;let poller=null;
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
async function request(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data}
function showPage(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));history.replaceState(null,'',`#${name}`)}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));
function trainPayload(){return{preset:$('preset').value,steps:+$('steps').value,batch_size:+$('batch').value,seq_len:+$('seq').value,device:$('device').value,learning_rate:+$('lr').value,grad_accum:+$('accum').value,warmup_steps:+$('warmup').value,weight_decay:+$('decay').value,grad_clip:+$('clip').value,precision:$('precision').value,checkpoint_every:+$('save').value,text:$('corpus').value}}
function updateEstimate(){if(!system)return;const row=system.presets.find(x=>x.id===$('preset').value);if(!row)return;$('estimate').innerHTML=`<b>${row.id.toUpperCase()} · ${(row.parameters/1e9).toFixed(2)}B 参数</b><br><span class="muted small">预计训练内存 ${row.training_memory_gb} GB · 本机 ${row.system_memory_gb} GB</span><br><span class="badge">${row.can_train_here?'本机可尝试':'建议远程 GPU'}</span>`}
async function refreshSystem(){system=await request('/api/system');$('serverAddress').textContent=location.host;$('baseUrl').textContent=`${location.origin}/v1`;renderModels(system.models);updateEstimate();updateTraining(system.training);$('apiModel').textContent=system.active_model||'尚未加载';$('chatModelBadge').textContent=system.active_model||'未加载'}
function renderModels(rows){const box=$('models');if(!rows.length){box.innerHTML='<div class="status muted small">还没有模型。完成一次训练后会出现在这里。</div>';return}box.innerHTML=rows.map(x=>`<div class="model"><div><b>${x.id}</b><span class="muted small">${(x.size_bytes/1048576).toFixed(1)} MB</span></div><button class="button" onclick="loadModel('${x.id}')">${x.active?'已加载':'加载'}</button></div>`).join('')}
async function loadModel(id){toast('正在从本机加载模型…');try{await request('/api/models/load',{method:'POST',body:JSON.stringify({model:id})});await refreshSystem();toast('模型已加载')}catch(e){toast(e.message)}}
function addMessage(role,text){const empty=$('messages').querySelector('.empty');if(empty)empty.remove();const el=document.createElement('div');el.className=`bubble ${role}`;el.textContent=text;$('messages').appendChild(el);$('messages').scrollTop=$('messages').scrollHeight}
async function send(){const prompt=$('prompt').value.trim();if(!prompt)return;$('prompt').value='';addMessage('user',prompt);$('sendButton').disabled=true;try{const data=await request('/api/chat',{method:'POST',body:JSON.stringify({prompt,max_tokens:128})});addMessage('assistant',data.content||'（模型没有生成可显示的文本）');await refreshSystem()}catch(e){addMessage('assistant',`错误：${e.message}`)}finally{$('sendButton').disabled=false;$('prompt').focus()}}
$('sendButton').onclick=send;$('prompt').onkeydown=e=>{if(e.key==='Enter')send()};$('refreshModels').onclick=refreshSystem;$('preset').onchange=updateEstimate;
$('startTraining').onclick=async()=>{try{await request('/api/training/start',{method:'POST',body:JSON.stringify(trainPayload())});toast('训练已在本机开始');startPolling()}catch(e){toast(e.message)}};
$('stopTraining').onclick=async()=>{try{await request('/api/training/stop',{method:'POST',body:'{}'});toast('正在停止并保存')}catch(e){toast(e.message)}};
$('createRemote').onclick=async()=>{try{const data=await request('/api/jobs',{method:'POST',body:JSON.stringify(trainPayload())});toast('远程任务包已生成');await refreshJobs();location.href=data.download}catch(e){toast(e.message)}};
function updateTraining(t){const pct=t.steps?Math.min(100,t.step/t.steps*100):0;$('trainingStatus').innerHTML=`<div class="status-line"><b>${({idle:'待机',running:'训练中',completed:'已完成',stopped:'已停止',failed:'失败'})[t.status]||t.status}</b><span>${t.step||0} / ${t.steps||0}</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="muted small" style="margin-top:9px">${t.message||''}${t.loss==null?'':` · loss ${Number(t.loss).toFixed(4)}`}</div>`;if(t.status!=='running'&&poller){clearInterval(poller);poller=null;refreshSystem()}}
function startPolling(){if(poller)clearInterval(poller);poller=setInterval(async()=>{try{updateTraining(await request('/api/training'))}catch{}},800)}
async function refreshJobs(){const rows=await request('/api/jobs');$('jobs').innerHTML=rows.length?rows.map(x=>`<div class="api-row"><span>${x.job_id}</span><a href="/api/jobs/${x.job_id}/download">下载</a></div>`).join(''):'暂无任务'}
document.querySelectorAll('.copy').forEach(button=>button.onclick=()=>{const text=button.parentElement.innerText.replace('复制','').trim();navigator.clipboard.writeText(text);toast('已复制')});
(async()=>{showPage(location.hash.slice(1)||'chat');try{await Promise.all([refreshSystem(),refreshJobs()]);if(system.training.status==='running')startPolling()}catch(e){toast(e.message)}})();
</script></body></html>'''
